# azure-pipelines.yml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: github-repo
      type: github
      name: VishnuReddyV92/azure-static-website
      endpoint: github-oauth-connection

pool:
  vmImage: 'ubuntu-latest'

variables:
  storageAccountName: 'staticwebsiteaccount'
  resourceGroup: 'rg-static-website'  

steps:
# Checkout code from GitHub
- checkout: github-repo
  displayName: 'Checkout Code from GitHub'

# Display repository info
- script: |
    echo "Building from GitHub repository: $(Build.Repository.Name)"
    echo "Branch: $(Build.SourceBranchName)"
    echo "Commit: $(Build.SourceVersion)"
  displayName: 'Display Repository Information'

# List files (for verification)
- script: |
    echo "Files in repository:"
    find . -type f -name "*.html" -o -name "*.css" -o -name "*.yml" | sort
  displayName: 'List Project Files'

# Validate we have the necessary files
- script: |
    if [ ! -f "index.html" ]; then
      echo "ERROR: index.html not found!"
      exit 1
    fi
    if [ ! -f "css/styles.css" ]; then
      echo "ERROR: css/styles.css not found!"
      exit 1
    fi
    echo "All required files found!"
  displayName: 'Validate Required Files'

# Create deployment artifact
- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.html
      **/*.css
      **/*.js
      **/*.png
      **/*.jpg
      **/*.svg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

# Publish build artifact (optional, for debugging)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'

# FIXED: Replace AzureCLI with AzureFileCopy (recommended approach)
- task: AzureFileCopy@4
  displayName: 'Deploy to Azure Storage Static Website'
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)'
    azureSubscription: 'azure-static-website-connection'
    Destination: 'AzureBlob'
    storage: '$(storageAccountName)'
    ContainerName: '$web'
    BlobPrefix: ''
    CleanTargetBeforeCopy: true

# FIXED: Simple success message
- script: |
    echo "🎉 Deployment completed successfully!"
    echo "🌐 Your static website is now live at:"
    echo "https://$(storageAccountName).z6.web.core.windows.net"
  displayName: 'Display Website URL'
