# azure-pipelines.yml
trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: github-repo
      type: github
      name: VishnuReddyV92/azure-static-website
      endpoint: github-oauth-connection

pool:
  vmImage: 'ubuntu-latest'

variables:
  storageAccountName: 'staticwebsiteaccount'
  resourceGroup: 'rg-static-website'

steps:
# Checkout code from GitHub
- checkout: github-repo
  displayName: 'Checkout Code from GitHub'

# Display repository info
- script: |
    echo "Building from GitHub repository: $(Build.Repository.Name)"
    echo "Branch: $(Build.SourceBranchName)"
    echo "Commit: $(Build.SourceVersion)"
  displayName: 'Display Repository Information'

# List files (for verification)
- script: |
    echo "Files in repository:"
    find . -type f -name "*.html" -o -name "*.css" -o -name "*.yml" | sort
  displayName: 'List Project Files'

# Validate we have the necessary files
- script: |
    if [ ! -f "index.html" ]; then
      echo "ERROR: index.html not found!"
      exit 1
    fi
    if [ ! -f "css/styles.css" ]; then
      echo "ERROR: css/styles.css not found!"
      exit 1
    fi
    echo "All required files found!"
  displayName: 'Validate Required Files'

# Create deployment artifact
- task: CopyFiles@2
  displayName: 'Copy Files to Artifact Directory'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*.html
      **/*.css
      **/*.js
      **/*.png
      **/*.jpg
      **/*.svg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    OverWrite: true

# Publish build artifact (optional, for debugging)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'website'
    publishLocation: 'Container'

# FIXED: Use Azure CLI with proper quotes and error handling for Linux
- task: AzureCLI@2
  displayName: 'Deploy to Azure Storage Static Website'
  inputs:
    azureSubscription: 'azure-static-website-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Starting deployment to Azure Storage..."
      echo "Storage Account: $(storageAccountName)"
      echo "Resource Group: $(resourceGroup)"
      
      # FIXED: Added proper quotes and error handling
      echo "Uploading files to Azure Storage..."
      az storage blob upload-batch \
        --account-name "$(storageAccountName)" \
        --source "$(Build.ArtifactStagingDirectory)" \
        --destination '$web' \
        --overwrite
      
      if [ $? -eq 0 ]; then
        echo "✅ Files uploaded successfully!"
      else
        echo "❌ File upload failed!"
        exit 1
      fi
      
      echo "🎉 Deployment completed successfully!"
      echo "🌐 Your static website is now live at:"
      echo "https://$(storageAccountName).z6.web.core.windows.net"
      
      # Optional: List the uploaded files for verification
      echo ""
      echo "Uploaded files:"
      az storage blob list \
        --account-name "$(storageAccountName)" \
        --container-name '$web' \
        --query "[].name" \
        --output table

# Final success message
- script: |
    echo "=========================================="
    echo "🚀 CI/CD PIPELINE COMPLETED SUCCESSFULLY!"
    echo "=========================================="
    echo "Your static website has been deployed to:"
    echo "https://$(storageAccountName).z6.web.core.windows.net"
    echo ""
    echo "Next steps:"
    echo "1. Open the URL above in your browser"
    echo "2. Verify all pages work correctly"
    echo "3. Celebrate! 🎉"
  displayName: 'Pipeline Success'
